const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

// Reaction events
const MESSAGE_REACTION_ADDED = "MESSAGE_REACTION_ADDED";
const MESSAGE_REACTION_REMOVED = "MESSAGE_REACTION_REMOVED";

// Reply events
const MESSAGE_REPLY = "MESSAGE_REPLY";

// Emoji effect event
const EMOJI_EFFECT = "EMOJI_EFFECT";

// Emoji combo event (both users sent the same emoji)
const EMOJI_COMBO = "EMOJI_COMBO";

// Emoji animation event (user triggered animation from picker)
const EMOJI_ANIMATION = "EMOJI_ANIMATION";

// Delete message event
const MESSAGE_DELETED = "MESSAGE_DELETED";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  MESSAGE_REACTION_ADDED,
  MESSAGE_REACTION_REMOVED,
  MESSAGE_REPLY,
  EMOJI_EFFECT,
  EMOJI_COMBO,
  EMOJI_ANIMATION,
  MESSAGE_DELETED,
};
